# Generated by Django 3.0.4 on 2020-03-24 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationlist',
            name='last_interaction',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
