# Generated by Django 3.0.4 on 2020-05-24 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_messages', '0003_auto_20200324_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_interaction',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
