# Generated by Django 2.2.5 on 2020-01-06 11:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20191011_1604'),
        ('communities', '0005_auto_20200106_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grouparticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('pubdate', models.DateTimeField(default=datetime.datetime(2020, 1, 6, 14, 37, 4, 696839), verbose_name='date published')),
            ],
        ),
        migrations.RemoveField(
            model_name='articlelist',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='articlelist',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouplist',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='grouplist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscriberlist',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subscriberlist',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='group',
            name='subscribers',
            field=models.ManyToManyField(blank=True, to='UserProfile.Profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 14, 37, 4, 695838), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleList',
        ),
        migrations.DeleteModel(
            name='GroupList',
        ),
        migrations.DeleteModel(
            name='SubscriberList',
        ),
        migrations.AddField(
            model_name='grouparticle',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.Group'),
        ),
    ]
