# Generated by Django 2.2.5 on 2020-01-06 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_auto_20200106_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('pubdate', models.DateTimeField(default=datetime.datetime(2020, 1, 6, 18, 45, 30, 696652), verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 18, 45, 30, 695652), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Grouparticle',
        ),
        migrations.AddField(
            model_name='group',
            name='articles',
            field=models.ManyToManyField(blank=True, to='communities.Article'),
        ),
    ]
