# Generated by Django 2.2.5 on 2020-01-06 15:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_auto_20200106_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('pubdate', models.DateTimeField(default=datetime.datetime(2020, 1, 6, 18, 58, 11, 550490), verbose_name='date published')),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='articles',
        ),
        migrations.AlterField(
            model_name='group',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 18, 58, 11, 549489), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='grouparticle',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.Group'),
        ),
    ]
