# Generated by Django 2.2.5 on 2020-01-07 05:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20191011_1604'),
        ('communities', '0010_auto_20200106_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouparticle',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='UserProfile.Profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 8, 51, 7, 194226), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='grouparticle',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 8, 51, 7, 195227), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pubdate', models.DateTimeField(default=datetime.datetime(2020, 1, 7, 8, 51, 7, 196228), verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UserProfile.Profile')),
            ],
        ),
    ]
