# Generated by Django 2.2.5 on 2020-01-07 06:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20191011_1604'),
        ('communities', '0011_auto_20200107_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pubdate', models.DateTimeField(default=datetime.datetime(2020, 1, 7, 9, 6, 26, 490957), verbose_name='date published')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='UserProfile.Profile')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usercomments', to='UserProfile.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 9, 6, 26, 488956), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='grouparticle',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='communities.Group'),
        ),
        migrations.AlterField(
            model_name='grouparticle',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 9, 6, 26, 489956), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
