# Generated by Django 2.2.5 on 2020-01-11 16:40

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0025_auto_20200111_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subrequests',
            field=models.ManyToManyField(blank=True, related_name='subrequests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 19, 40, 58, 501798), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='grouparticle',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 19, 40, 58, 504801), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='groupcomment',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 19, 40, 58, 504801), verbose_name='date published'),
        ),
    ]
