# Generated by Django 2.2.5 on 2020-01-12 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0028_auto_20200112_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouparticle',
            name='allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 19, 19, 8, 979806), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='grouparticle',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 19, 19, 8, 981807), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='groupcomment',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 19, 19, 8, 982808), verbose_name='date published'),
        ),
    ]
