# Generated by Django 2.2.5 on 2020-01-22 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0032_auto_20200113_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='allowarticles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 16, 49, 51, 275712), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='grouparticle',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 16, 49, 51, 278714), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='groupcomment',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 16, 49, 51, 279715), verbose_name='date published'),
        ),
    ]
