# Generated by Django 2.2.5 on 2020-01-31 18:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0034_auto_20200131_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='groups/group_files')),
            ],
        ),
        migrations.AlterField(
            model_name='articlefile',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='communities.GroupArticle'),
        ),
        migrations.AlterField(
            model_name='articlefile',
            name='file',
            field=models.FileField(blank=True, upload_to='groups/articles_files'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, upload_to='groups/groupimages'),
        ),
        migrations.AlterField(
            model_name='group',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 21, 44, 51, 654165), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='grouparticle',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 21, 44, 51, 657168), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='groupcomment',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 21, 44, 51, 659170), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='GroupImages',
        ),
        migrations.AddField(
            model_name='groupfile',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='communities.Group'),
        ),
    ]
