# Generated by Django 2.2.5 on 2020-02-17 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0036_auto_20200131_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefile',
            name='name',
            field=models.CharField(default='filename', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupfile',
            name='name',
            field=models.CharField(default='filename', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='allowarticles',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default=False, upload_to='groups/groupimages'),
        ),
        migrations.AlterField(
            model_name='group',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 12, 33, 39, 409219), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='grouparticle',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 12, 33, 39, 412221), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='groupcomment',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 12, 33, 39, 413222), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='GroupImage',
        ),
    ]
