# Generated by Django 3.0.7 on 2020-06-15 19:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0037_auto_20200217_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='banned',
            field=models.ManyToManyField(blank=True, related_name='groups_banned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='groups_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 22, 22, 37, 941258), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='group',
            name='subrequests',
            field=models.ManyToManyField(blank=True, related_name='groups_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='groups_subs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grouparticle',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 22, 22, 37, 943613), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='groupcomment',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 22, 22, 37, 945124), verbose_name='date published'),
        ),
    ]
