# Generated by Django 3.0.4 on 2020-06-18 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0039_auto_20200617_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 14, 29, 9, 364305), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='grouparticle',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 14, 29, 9, 367395), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='groupcomment',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 14, 29, 9, 368733), verbose_name='date published'),
        ),
    ]
