# Generated by Django 2.2.2 on 2019-06-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=20000)),
                ('post_name', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
