# Generated by Django 2.2.5 on 2019-10-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
