# Generated by Django 3.0.4 on 2020-03-28 12:39

import UserProfile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20191011_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/static/profile.jpg', upload_to=UserProfile.models.user_directorypath),
        ),
    ]
