# Generated by Django 3.0.4 on 2020-06-18 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserProfile', '0004_privacysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blacklist',
            field=models.ManyToManyField(related_name='blacklists', to=settings.AUTH_USER_MODEL),
        ),
    ]
