# Generated by Django 2.2.5 on 2019-10-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_text', models.TextField()),
                ('not_name', models.CharField(max_length=100)),
                ('not_date', models.DateTimeField(verbose_name='date published')),
                ('not_link', models.CharField(max_length=200)),
                ('not_checked', models.BooleanField(default=True)),
            ],
        ),
    ]
