# Generated by Django 2.2.3 on 2019-11-03 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='not_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 17, 6, 23, 224946), verbose_name='date published'),
        ),
    ]
