# Generated by Django 2.2.7 on 2019-12-31 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20191103_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='not_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 23, 29, 4, 232203), verbose_name='date published'),
        ),
    ]
