# Generated by Django 3.0.4 on 2020-03-29 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_auto_20200329_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='not_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 20, 58, 18, 706504), verbose_name='date published'),
        ),
    ]
