# Generated by Django 3.0.4 on 2020-03-29 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_auto_20200329_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='not_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 21, 11, 3, 590012), verbose_name='date published'),
        ),
    ]
