# Generated by Django 3.0.4 on 2020-05-24 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_auto_20200329_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='not_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 16, 54, 35, 207516), verbose_name='date published'),
        ),
    ]
