# Generated by Django 3.0.7 on 2020-06-15 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0019_auto_20200524_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='not_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 22, 22, 37, 945834), verbose_name='date published'),
        ),
    ]
