# Generated by Django 3.0.4 on 2020-06-18 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0021_auto_20200617_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='not_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 14, 29, 9, 369427), verbose_name='date published'),
        ),
    ]
