# Generated by Django 3.0.7 on 2020-06-19 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0022_auto_20200618_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='not_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 21, 42, 33, 952474), verbose_name='date published'),
        ),
    ]
